import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Body from '../components/Body'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Click2Connect</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body/>
      
    </div>
  )
}
